from tkinter import *
from tkinter import messagebox
from tkinter import ttk
import pymysql
import random

root=Tk()
root.minsize(height=750,width=1500)
root.maxsize(height=750,width=1500)
#ADDING A SCROLLBAR
scrollbary = Scrollbar(root)
scrollbarx = Scrollbar(root, orient=HORIZONTAL)
def tab1():
    def tab2():
        l1.destroy()
        
        b1.destroy()
        ll=Label(root,text="Railway Reservation",font=("Bold",50),fg="black",bg="orange",bd=6)
        ll.place(x=450,y=0)
        def password():
            exitbutton.destroy()
            def login():
                username=e1.get()
                password=e2.get()
                if username=="" and password=="":
                    messagebox.showinfo("","Blank Not Allowed")
                    exitbutton=Button(root,text="Exit",font=("Bold",20),fg="black",bg="orange",command=root.destroy)
                    exitbutton.place(x=120,y=200)
                elif username=="dev" and password=="12345":
                    messagebox.showinfo("","Login Successfull")
                    def server():
                        ll.destroy()
                        b5.destroy()
                        
                        
                        def add():
                            a1=e3.get()  #name
                            a2=e4.get()  #adharno
                            a3=e5.get()  #phoneno
                            a4=e6.get()  #email
                            a5=e7.get()  #gender
                            a6=e8.get()  #no of seat
                            a7=e9.get()  #child
                            a8=e10.get()  #adult
                            a9=e11.get() #from
                            a10=e12.get() #to
                            a11=e13.get()#trainname
                            a12=e14.get()#train number
                            a13=e15.get()#arrival
                            a14=e16.get()#departure
                            a15=e17.get()#line
                            a16=e18.get()#date
                            a17=e19.get()#coach type
                            a18=e20.get()#coach no
                            a19=e21.get()#cost
                            a20=e22.get()#seat no
                            a21=e23.get()   #traintype
                            connect1=pymysql.connect(host="localhost",user="root",password="12345",database="reservation")
                            con=connect1.cursor()

                            try:
                                sql="INSERT INTO record(name,adharno,phoneno,email,gender,noofseat,child,adult,start,endpoint,trainname,trainnumber,arrival,departure,line,journey_date,coachtype,coachno,cost,seatno,train_type) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"
                                val=(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20,a21)
                                con.execute(sql,val)
                                connect1.commit()
                                messagebox.showinfo("information","Record inserted successfully...")
                                e3.delete(0,END)
                                e4.delete(0,END)
                                e5.delete(0,END)
                                e6.delete(0,END)
                                e7.delete(0,END)
                                e8.delete(0,END)
                                e9.delete(0,END)
                                e10.delete(0,END)
                                e11.delete(0,END)
                                e12.delete(0,END)
                                e13.delete(0,END)
                                e14.delete(0,END)
                                e15.delete(0,END)
                                e16.delete(0,END)
                                e17.delete(0,END)
                                e18.delete(0,END)
                                e19.delete(0,END)
                                e20.delete(0,END)
                                e21.delete(0,END)
                                e22.delete(0,END)
                                e23.delete(0,END)
                                e3.focus_set()
                            except Exception as e:
                                print(e)
                                connect1.rollback()
                                connect1.close()
                        def show():
                            connect1=pymysql.connect(host="localhost",user="root",password="12345",database="reservation")
                            con=connect1.cursor()
                            con.execute("SELECT name,adharno,phoneno,email,gender,noofseat,child,adult,start,endpoint,trainname,trainnumber,arrival,departure,line,journey_date,coachtype,coachno,cost,seatno,train_type FROM record")
                            records=con.fetchall()
                            #print(records)
                            for l,(name,adharno,phoneno,email,gender,noofseat,child,adult,start,endpoint,trainname,trainnumber,arrival,departure,line,journey_date,coachtype,coachno,cost,seatno,train_type) in enumerate(records,start=1):
                                listBox.insert("","end",values=((name,adharno,phoneno,email,gender,noofseat,child,adult,start,endpoint,trainname,trainnumber,arrival,departure,line,journey_date,coachtype,coachno,cost,seatno,train_type)))
                            connect1.close()  
                        def search_update():
                            backbutton.destroy()
                            e3.destroy()
                            e4.destroy()
                            e5.destroy()
                            e6.destroy()
                            e7.destroy()
                            e8.destroy()
                            e9.destroy()
                            e10.destroy()
                            e11.destroy()
                            e12.destroy()
                            e13.destroy()
                            e14.destroy()
                            e15.destroy()
                            e16.destroy()
                            e17.destroy()
                            e18.destroy()
                            e19.destroy()
                            e20.destroy()
                            e21.destroy()
                            e22.destroy()
                            e23.destroy()
                            l4.destroy()
                            listBox.destroy()
                            b6.destroy()
                            b7.destroy()
                            b8.destroy()
                            
                            scrollbarx.destroy()
                            scrollbary.destroy()
                            lable=Label(root,text="enter the phone number of the person to be updated")
                            lable.place(x=20,y=10)
                            lable1=Label(root,text="phoneno: ")
                            lable1.place(x=20,y=40)
                            entry1=Entry(root,bd=7)
                            entry1.place(x=100,y=40)
                            def update_record():                                
                                button1.destroy()
                                
                                lable4=Label(root,text="CAUTION! you have to enter all record wheather it contain the same value,else it will be deleated",font=("Bold",20),fg="black",bg="red")
                                lable4.place(x=20,y=400)
                                lable2=Label(root,text="adharno: ")
                                lable2.place(x=20,y=450)
                                entry2=Entry(root,bd=7)
                                entry2.place(x=130,y=450)
                                w1=Label(root,text="name:",font=("Bold",12),fg="black",bg="orange")
                                w1.place(x=20,y=500)
                                w2=Label(root,text="adhare.no:",font=("Bold",12),fg="black",bg="orange")
                                w2.place(x=10,y=550)
                                w3=Label(root,text="phone.no:",font=("Bold",12),fg="black",bg="orange")
                                w3.place(x=10,y=600)
                                w4=Label(root,text="email:",font=("Bold",12),fg="black",bg="orange")
                                w4.place(x=10,y=650)
                                w5=Label(root,text="gender:",font=("Bold",12),fg="black",bg="orange")
                                w5.place(x=300,y=500)
                                w6=Label(root,text="no of seat:",font=("Bold",12),fg="black",bg="orange")
                                w6.place(x=300,y=550)
                                w7=Label(root,text="child:",font=("Bold",12),fg="black",bg="orange")
                                w7.place(x=300,y=600)
                                w8=Label(root,text="adult:",font=("Bold",12),fg="black",bg="orange")
                                w8.place(x=300,y=650)
                                w9=Label(root,text="from:",font=("Bold",12),fg="black",bg="orange")
                                w9.place(x=550,y=500)
                                w10=Label(root,text="to:",font=("Bold",12),fg="black",bg="orange")
                                w10.place(x=550,y=550)
                                w11=Label(root,text="train name:",font=("Bold",12),fg="black",bg="orange")
                                w11.place(x=550,y=600)
                                w12=Label(root,text="train number:",font=("Bold",12),fg="black",bg="orange")
                                w12.place(x=550,y=650)
                                w13=Label(root,text="arrival:",font=("Bold",12),fg="black",bg="orange")
                                w13.place(x=800,y=500)
                                w14=Label(root,text="departure:",font=("Bold",12),fg="black",bg="orange")
                                w14.place(x=800,y=550)
                                w15=Label(root,text="line:",font=("Bold",12),fg="black",bg="orange")
                                w15.place(x=800,y=600)
                                w16=Label(root,text="date:",font=("Bold",12),fg="black",bg="orange")
                                w16.place(x=800,y=650)
                                w17=Label(root,text="coach type:",font=("Bold",12),fg="black",bg="orange")
                                w17.place(x=1050,y=500)
                                w18=Label(root,text="coach no:",font=("Bold",12),fg="black",bg="orange")
                                w18.place(x=1050,y=550)
                                w19=Label(root,text="cost:",font=("Bold",12),fg="black",bg="orange")
                                w19.place(x=1050,y=600)
                                w20=Label(root,text="seat no:",font=("Bold",12),fg="black",bg="orange")
                                w20.place(x=1050,y=650)
                                w21=Label(root,text="train type:",font=("Bold",12),fg="black",bg="orange")
                                w21.place(x=10,y=700)
                                v1=Entry(root,bd=7)
                                v1.place(x=130,y=500)
                                v2=Entry(root,bd=7)
                                v2.place(x=130,y=550)
                                v3=Entry(root,bd=7)
                                v3.place(x=130,y=600)
                                v4=Entry(root,bd=7)
                                v4.place(x=130,y=650)
                                v5=Entry(root,bd=7)
                                v5.place(x=400,y=500)
                                v6=Entry(root,bd=7)
                                v6.place(x=400,y=550)
                                v7=Entry(root,bd=7)
                                v7.place(x=400,y=600)
                                v8=Entry(root,bd=7)
                                v8.place(x=400,y=650)
                                v9=Entry(root,bd=7)
                                v9.place(x=650,y=500)
                                v10=Entry(root,bd=7)
                                v10.place(x=650,y=550)
                                v11=Entry(root,bd=7)
                                v11.place(x=650,y=600)
                                v12=Entry(root,bd=7)
                                v12.place(x=650,y=650)
                                v13=Entry(root,bd=7)
                                v13.place(x=900,y=500)
                                v14=Entry(root,bd=7)
                                v14.place(x=900,y=550)
                                v15=Entry(root,bd=7)
                                v15.place(x=900,y=600)
                                v16=Entry(root,bd=7)
                                v16.place(x=900,y=650)
                                v17=Entry(root,bd=7)
                                v17.place(x=1150,y=500)
                                v18=Entry(root,bd=7)
                                v18.place(x=1150,y=550)
                                v19=Entry(root,bd=7)
                                v19.place(x=1150,y=600)
                                v20=Entry(root,bd=7)
                                v20.place(x=1150,y=650)
                                v21=Entry(root,bd=7)
                                v21.place(x=130,y=700)
                                def back2():
                                    lable.destroy()
                                    lable1.destroy()
                                    entry1.destroy()
                                    lable4.destroy()
                                    lable2.destroy()
                                    entry2.destroy()
                                    w1.destroy()
                                    w2.destroy()
                                    w3.destroy()
                                    w4.destroy()
                                    w5.destroy()
                                    w6.destroy()
                                    w7.destroy()
                                    w8.destroy()
                                    w9.destroy()
                                    w10.destroy()
                                    w11.destroy()
                                    w12.destroy()
                                    w13.destroy()
                                    w14.destroy()
                                    w15.destroy()
                                    w16.destroy()
                                    w17.destroy()
                                    w18.destroy()
                                    w19.destroy()
                                    w20.destroy()
                                    w21.destroy()
                                    v1.destroy()
                                    v2.destroy()
                                    v3.destroy()
                                    v4.destroy()
                                    v5.destroy()
                                    v6.destroy()
                                    v7.destroy()
                                    v8.destroy()
                                    v9.destroy()
                                    v10.destroy()
                                    v11.destroy()
                                    v12.destroy()
                                    v13.destroy()
                                    v14.destroy()
                                    v15.destroy()
                                    v16.destroy()
                                    v17.destroy()
                                    v18.destroy()
                                    v19.destroy()
                                    v20.destroy()
                                    v21.destroy()
                                    
                                def update():
                                    g1=v1.get()
                                    g2=v2.get()
                                    g3=v3.get()
                                    g4=v4.get()
                                    g5=v5.get()
                                    g6=v6.get()
                                    g7=v7.get()
                                    g8=v8.get()
                                    g9=v9.get()
                                    g10=v10.get()
                                    g11=v11.get()
                                    g12=v12.get()
                                    g13=v13.get()
                                    g14=v14.get()
                                    g15=v15.get()
                                    g16=v16.get()
                                    g17=v17.get()
                                    g18=v18.get()
                                    g19=v19.get()
                                    g20=v20.get()
                                    g21=v21.get()
                                    gg2=entry2.get()
                                    connect1=pymysql.connect(host="localhost",user="root",password="12345",database="reservation")
                                    con=connect1.cursor()
                                    try:
                                        sql="""UPDATE record SET name=%s,adharno=%s,phoneno=%s,email=%s,gender=%s,noofseat=%s,child=%s,adult=%s,start=%s,endpoint=%s,trainname=%s,trainnumber=%s,arrival=%s,departure=%s,line=%s,journey_date=%s,coachtype=%s,coachno=%s,cost=%s,seatno=%s,train_type=%s WHERE adharno=%s"""
                                        val=(g1,g2,g3,g4,g5,g6,g7,g8,g9,g10,g11,g12,g13,g14,g15,g16,g17,g18,g19,g20,g21,gg2)
                                        con.execute(sql,val)
                                        connect1.commit()
                                        messagebox.showinfo("Record","updated successfully...")
                                        v1.delete(0,END)
                                        v2.delete(0,END)
                                        v3.delete(0,END)
                                        v4.delete(0,END)
                                        v5.delete(0,END)
                                        v6.delete(0,END)
                                        v7.delete(0,END)
                                        v8.delete(0,END)
                                        v9.delete(0,END)
                                        v10.delete(0,END)
                                        v11.delete(0,END)
                                        v12.delete(0,END)
                                        v13.delete(0,END)
                                        v14.delete(0,END)
                                        v15.delete(0,END)
                                        v16.delete(0,END)
                                        v17.delete(0,END)
                                        v18.delete(0,END)
                                        v19.delete(0,END)
                                        v20.delete(0,END)
                                        v21.delete(0,END)
                                        v1.focus_set()
                                    except Exception as e:
                                            print(e)
                                            connect1.rollback()
                                            connect1.close()                                    
                                button2=Button(root,text="update",height=1,width=15,bd=6,font=("Bold",12),fg="black",bg="orange",command=update)
                                button2.place(x=1350,y=550)
                                
                                def searchpart():
                                    l4.destroy()
                                    l5.destroy()
                                    l6.destroy()
                                    l7.destroy()
                                    l8.destroy()
                                    l9.destroy()
                                    l10.destroy()
                                    l11.destroy()
                                    l12.destroy()
                                    l13.destroy()
                                    l14.destroy()
                                    l15.destroy()
                                    l16.destroy()
                                    l17.destroy()
                                    l18.destroy()
                                    l19.destroy()
                                    l20.destroy()
                                    l21.destroy()
                                    l22.destroy()
                                    l23.destroy()
                                    l24.destroy()
                                    l25.destroy()

                                    phoneno=entry1.get()
                                    connect1=pymysql.connect(host="localhost",user="root",password="12345",database="reservation")
                                    con=connect1.cursor()
                                    con.execute("SELECT * FROM record")
                                    record=con.fetchall()
                                    record1=()

                                    for i in record:
                                        if i[2]==phoneno:
                                            record1=i       
                                    ww1=Label(root,text=record1[0],font=("Bold",12),fg="black",bg="white")
                                    ww1.place(x=110,y=100)
                                    ww2=Label(root,text=record1[1],font=("Bold",12),fg="black",bg="white")
                                    ww2.place(x=110,y=150)
                                    ww3=Label(root,text=record1[2],font=("Bold",12),fg="black",bg="white")
                                    ww3.place(x=110,y=200)
                                    ww4=Label(root,text=record1[3],font=("Bold",12),fg="black",bg="white")
                                    ww4.place(x=110,y=250)
                                    ww5=Label(root,text=record1[4],font=("Bold",12),fg="black",bg="white")
                                    ww5.place(x=400,y=100)
                                    ww6=Label(root,text=record1[5],font=("Bold",12),fg="black",bg="white")
                                    ww6.place(x=400,y=150)
                                    ww7=Label(root,text=record1[6],font=("Bold",12),fg="black",bg="white")
                                    ww7.place(x=400,y=200)
                                    ww8=Label(root,text=record1[7],font=("Bold",12),fg="black",bg="white")
                                    ww8.place(x=400,y=250)
                                    ww9=Label(root,text=record1[8],font=("Bold",12),fg="black",bg="white")
                                    ww9.place(x=690,y=100)
                                    ww10=Label(root,text=record1[9],font=("Bold",12),fg="black",bg="white")
                                    ww10.place(x=690,y=150)
                                    ww11=Label(root,text=record1[10],font=("Bold",12),fg="black",bg="white")
                                    ww11.place(x=690,y=200)
                                    ww12=Label(root,text=record1[11],font=("Bold",12),fg="black",bg="white")
                                    ww12.place(x=690,y=250)
                                    ww13=Label(root,text=record1[12],font=("Bold",12),fg="black",bg="white")
                                    ww13.place(x=900,y=100)
                                    ww14=Label(root,text=record1[13],font=("Bold",12),fg="black",bg="white")
                                    ww14.place(x=900,y=150)
                                    ww15=Label(root,text=record1[14],font=("Bold",12),fg="black",bg="white")
                                    ww15.place(x=900,y=200)
                                    ww16=Label(root,text=record1[15],font=("Bold",12),fg="black",bg="white")
                                    ww16.place(x=900,y=250)
                                    ww17=Label(root,text=record1[16],font=("Bold",12),fg="black",bg="white")
                                    ww17.place(x=1200,y=100)
                                    ww18=Label(root,text=record1[17],font=("Bold",12),fg="black",bg="white")
                                    ww18.place(x=1200,y=150)
                                    ww19=Label(root,text=record1[18],font=("Bold",12),fg="black",bg="white")
                                    ww19.place(x=1200,y=200)
                                    ww20=Label(root,text=record1[19],font=("Bold",12),fg="black",bg="white")
                                    ww20.place(x=1200,y=250)
                                    ww21=Label(root,text=record1[20],font=("Bold",12),fg="black",bg="white")
                                    ww21.place(x=110,y=300)                                                                      
                                    connect1.close()
                                    r5=Label(root,text="name:",font=("Bold",12),fg="black",bg="orange")
                                    r5.place(x=20,y=100)
                                    r6=Label(root,text="adhare.no:",font=("Bold",12),fg="black",bg="orange")
                                    r6.place(x=10,y=150)
                                    r7=Label(root,text="phone.no:",font=("Bold",12),fg="black",bg="orange")
                                    r7.place(x=10,y=200)
                                    r8=Label(root,text="email:",font=("Bold",12),fg="black",bg="orange")
                                    r8.place(x=10,y=250)
                                    r9=Label(root,text="gender:",font=("Bold",12),fg="black",bg="orange")
                                    r9.place(x=300,y=100)
                                    r10=Label(root,text="no of seat:",font=("Bold",12),fg="black",bg="orange")
                                    r10.place(x=300,y=150)
                                    r11=Label(root,text="child:",font=("Bold",12),fg="black",bg="orange")
                                    r11.place(x=300,y=200)
                                    r12=Label(root,text="adult:",font=("Bold",12),fg="black",bg="orange")
                                    r12.place(x=300,y=250)
                                    r13=Label(root,text="from:",font=("Bold",12),fg="black",bg="orange")
                                    r13.place(x=550,y=100)
                                    r14=Label(root,text="to:",font=("Bold",12),fg="black",bg="orange")
                                    r14.place(x=550,y=150)
                                    r15=Label(root,text="train name:",font=("Bold",12),fg="black",bg="orange")
                                    r15.place(x=550,y=200)
                                    r16=Label(root,text="train number:",font=("Bold",12),fg="black",bg="orange")
                                    r16.place(x=550,y=250)
                                    r17=Label(root,text="arrival:",font=("Bold",12),fg="black",bg="orange")
                                    r17.place(x=800,y=100)
                                    r18=Label(root,text="departure:",font=("Bold",12),fg="black",bg="orange")
                                    r18.place(x=800,y=150)
                                    r19=Label(root,text="line:",font=("Bold",12),fg="black",bg="orange")
                                    r19.place(x=800,y=200)
                                    r20=Label(root,text="date:",font=("Bold",12),fg="black",bg="orange")
                                    r20.place(x=800,y=250)
                                    r21=Label(root,text="coach type:",font=("Bold",12),fg="black",bg="orange")
                                    r21.place(x=1050,y=100)
                                    r22=Label(root,text="coach no:",font=("Bold",12),fg="black",bg="orange")
                                    r22.place(x=1050,y=150)
                                    r23=Label(root,text="cost:",font=("Bold",12),fg="black",bg="orange")
                                    r23.place(x=1050,y=200)
                                    r24=Label(root,text="seat no:",font=("Bold",12),fg="black",bg="orange")
                                    r24.place(x=1050,y=250)
                                    r25=Label(root,text="train type:",font=("Bold",12),fg="black",bg="orange")
                                    r25.place(x=10,y=300)
                                    def back1():
                                        button1.destroy()
                                        ww1.destroy()
                                        ww2.destroy()
                                        ww3.destroy()
                                        ww4.destroy()
                                        ww5.destroy()
                                        ww6.destroy()
                                        ww7.destroy()
                                        ww8.destroy()
                                        ww9.destroy()
                                        ww10.destroy()
                                        ww11.destroy()
                                        ww12.destroy()
                                        ww13.destroy()
                                        ww14.destroy()
                                        ww15.destroy()
                                        ww16.destroy()
                                        ww17.destroy()
                                        ww18.destroy()
                                        ww19.destroy()
                                        ww20.destroy()
                                        ww21.destroy()
                                        r5.destroy()
                                        r6.destroy()
                                        r7.destroy()
                                        r8.destroy()
                                        r9.destroy()
                                        r10.destroy()
                                        r11.destroy()
                                        r12.destroy()
                                        r13.destroy()
                                        r14.destroy()
                                        r15.destroy()
                                        r16.destroy()
                                        r17.destroy()
                                        r18.destroy()
                                        r19.destroy()
                                        r20.destroy()
                                        r21.destroy()
                                        r22.destroy()
                                        r23.destroy()
                                        r24.destroy()
                                        r25.destroy()
                                        backbutton1.destroy()
                                        button3.destroy()
                                        button2.destroy()
                                        back2()
                                        server()
                                    backbutton1=Button(root,text="back",height=1,width=10,bd=6,font=("Bold",12),fg="black",bg="orange",command=back1)
                                    backbutton1.place(x=1350,y=250)
                                button3=Button(root,text="Enter",height=1,width=10,bd=6,font=("Bold",12),fg="black",bg="orange",command=searchpart)
                                button3.place(x=300,y=40)
                            button1=Button(root,text="update_search",height=1,width=15,bd=6,font=("Bold",12),fg="black",bg="orange",command=update_record)
                            button1.place(x=500,y=500)  


                            
                                                                            
                        def delete():
                            connect1=pymysql.connect(host="localhost",user="root",password="12345",database="reservation")
                            con=connect1.cursor()
                            selected_item=listBox.selection()[0]
                            
                            u_adharno=listBox.item(selected_item)["values"][2]
                            
                            del_query="DELETE FROM record WHERE phoneno=%s"
                            sel_data=(u_adharno)
                            con.execute(del_query,sel_data)
                            connect1.commit()
                            listBox.delete(selected_item)
                            messagebox.showinfo("success","data deleted")
                            
                        def Back():
                            l4.destroy()
                            l5.destroy()
                            l6.destroy()
                            l7.destroy()
                            l8.destroy()
                            l9.destroy()
                            l10.destroy()
                            l11.destroy()
                            l12.destroy()
                            l13.destroy()
                            l14.destroy()
                            l15.destroy()
                            l16.destroy()
                            l17.destroy()
                            l18.destroy()
                            l19.destroy()
                            l20.destroy()
                            l21.destroy()
                            l22.destroy()
                            l23.destroy()
                            l24.destroy()
                            l25.destroy()
                            e3.destroy()
                            e4.destroy()
                            e5.destroy()
                            e6.destroy()
                            e7.destroy()
                            e8.destroy()
                            e9.destroy()
                            e10.destroy()
                            e11.destroy()
                            e12.destroy()
                            e13.destroy()
                            e14.destroy()
                            e15.destroy()
                            e16.destroy()
                            e17.destroy()
                            e18.destroy()
                            e19.destroy()
                            e20.destroy()
                            e21.destroy()
                            e22.destroy()
                            e23.destroy()
                            b6.destroy()
                            b7.destroy()
                            b8.destroy()
                            scrollbarx.destroy()
                            scrollbary.destroy()
                            listBox.destroy()
                            backbutton.destroy()
                            tab2()
                        l4=Label(root,text="SERVER",fg="black",bg="orange",font=("Bold",50))
                        l4.place(x=550,y=0)
                        l5=Label(root,text="name:",font=("Bold",12),fg="black",bg="orange")
                        l5.place(x=20,y=100)
                        l6=Label(root,text="adhare.no:",font=("Bold",12),fg="black",bg="orange")
                        l6.place(x=10,y=150)
                        l7=Label(root,text="phone.no:",font=("Bold",12),fg="black",bg="orange")
                        l7.place(x=10,y=200)
                        l8=Label(root,text="email:",font=("Bold",12),fg="black",bg="orange")
                        l8.place(x=10,y=250)
                        l9=Label(root,text="gender:",font=("Bold",12),fg="black",bg="orange")
                        l9.place(x=300,y=100)
                        l10=Label(root,text="no of seat:",font=("Bold",12),fg="black",bg="orange")
                        l10.place(x=300,y=150)
                        l11=Label(root,text="child:",font=("Bold",12),fg="black",bg="orange")
                        l11.place(x=300,y=200)
                        l12=Label(root,text="adult:",font=("Bold",12),fg="black",bg="orange")
                        l12.place(x=300,y=250)
                        l13=Label(root,text="from:",font=("Bold",12),fg="black",bg="orange")
                        l13.place(x=550,y=100)
                        l14=Label(root,text="to:",font=("Bold",12),fg="black",bg="orange")
                        l14.place(x=550,y=150)
                        l15=Label(root,text="train name:",font=("Bold",12),fg="black",bg="orange")
                        l15.place(x=550,y=200)
                        l16=Label(root,text="train number:",font=("Bold",12),fg="black",bg="orange")
                        l16.place(x=550,y=250)
                        l17=Label(root,text="arrival:",font=("Bold",12),fg="black",bg="orange")
                        l17.place(x=800,y=100)
                        l18=Label(root,text="departure:",font=("Bold",12),fg="black",bg="orange")
                        l18.place(x=800,y=150)
                        l19=Label(root,text="line:",font=("Bold",12),fg="black",bg="orange")
                        l19.place(x=800,y=200)
                        l20=Label(root,text="date:",font=("Bold",12),fg="black",bg="orange")
                        l20.place(x=800,y=250)
                        l21=Label(root,text="coach type:",font=("Bold",12),fg="black",bg="orange")
                        l21.place(x=1050,y=100)
                        l22=Label(root,text="coach no:",font=("Bold",12),fg="black",bg="orange")
                        l22.place(x=1050,y=150)
                        l23=Label(root,text="cost:",font=("Bold",12),fg="black",bg="orange")
                        l23.place(x=1050,y=200)
                        l24=Label(root,text="seat no:",font=("Bold",12),fg="black",bg="orange")
                        l24.place(x=1050,y=250)
                        l25=Label(root,text="train type:",font=("Bold",12),fg="black",bg="orange")
                        l25.place(x=10,y=300)
                        e3=Entry(root,bd=7)
                        e3.place(x=130,y=100)
                        e4=Entry(root,bd=7)
                        e4.place(x=130,y=150)
                        e5=Entry(root,bd=7)
                        e5.place(x=130,y=200)
                        e6=Entry(root,bd=7)
                        e6.place(x=130,y=250)
                        e7=Entry(root,bd=7)
                        e7.place(x=400,y=100)
                        e8=Entry(root,bd=7)
                        e8.place(x=400,y=150)
                        e9=Entry(root,bd=7)
                        e9.place(x=400,y=200)
                        e10=Entry(root,bd=7)
                        e10.place(x=400,y=250)
                        e11=Entry(root,bd=7)
                        e11.place(x=650,y=100)
                        e12=Entry(root,bd=7)
                        e12.place(x=650,y=150)
                        e13=Entry(root,bd=7)
                        e13.place(x=650,y=200)
                        e14=Entry(root,bd=7)
                        e14.place(x=650,y=250)
                        e15=Entry(root,bd=7)
                        e15.place(x=900,y=100)
                        e16=Entry(root,bd=7)
                        e16.place(x=900,y=150)
                        e17=Entry(root,bd=7)
                        e17.place(x=900,y=200)
                        e18=Entry(root,bd=7)
                        e18.place(x=900,y=250)
                        e19=Entry(root,bd=7)
                        e19.place(x=1150,y=100)
                        e20=Entry(root,bd=7)
                        e20.place(x=1150,y=150)
                        e21=Entry(root,bd=7)
                        e21.place(x=1150,y=200)
                        e22=Entry(root,bd=7)
                        e22.place(x=1150,y=250)
                        e23=Entry(root,bd=7)
                        e23.place(x=130,y=300)
                        b6=Button(root,text="ADD",height=1,width=10,bd=6,font=("Bold",12),fg="black",bg="orange",command=add)
                        b6.place(x=1350,y=100)
                        b7=Button(root,text="search/update",height=1,width=12,bd=6,font=("Bold",12),fg="black",bg="orange",command=search_update)
                        b7.place(x=1350,y=150)
                        b8=Button(root,text="DELETE",height=1,width=10,bd=6,font=("Bold",12),fg="black",bg="orange",command=delete)
                        b8.place(x=1350,y=200)
                        backbutton=Button(root,text="back",height=1,width=10,bd=6,font=("Bold",12),fg="black",bg="orange",command=Back)
                        backbutton.place(x=1350,y=250)
                        scrollbarx=Scrollbar(root,orient=HORIZONTAL)
                        scrollbary=Scrollbar(root,orient=VERTICAL)
                        listBox=ttk.Treeview(root)
                        listBox.place(relx=0.05, rely=0.500,width=1300,height=310)

                        listBox.configure(yscrollcommand=scrollbary.set,xscrollcommand=scrollbarx.set)
                        listBox.configure(selectmode="extended")

                        scrollbarx.configure(command=listBox.xview)
                        scrollbary.configure(command=listBox.yview)

                        scrollbarx.place(relx=0.250,rely=0.922,width=651,height=20)
                        scrollbary.place(relx=0.934,rely=0.500,width=22,height=332)
                        listBox.configure(
                                columns=(
                                    "name",
                                    "adhar.no.",
                                    "phone.no.",
                                    "email",
                                    "gender",
                                    "no.of.seat",
                                    "child",
                                    "adult",
                                    "start",
                                    "endpoint",
                                    "trainname",
                                    "trainnumber",
                                    "arrival",
                                    "departure",
                                    "line",
                                    "journey_date",
                                    "coachtype",
                                    "coachno",
                                    "cost",
                                    "seatno",
                                    "train_type"
                                )
                        )
                        listBox.heading("#0",text="Srno.",anchor=W)
                        listBox.heading("name",text="Name",anchor=W)
                        listBox.heading("adhar.no.",text="adhar.no.",anchor=W)
                        listBox.heading("phone.no.",text="phone.no.",anchor=W)
                        listBox.heading("email",text="email",anchor=W)
                        listBox.heading("gender",text="gender",anchor=W)
                        listBox.heading("no.of.seat",text="no.of.seat",anchor=W)
                        listBox.heading("child",text="child",anchor=W)
                        listBox.heading("adult",text="adult",anchor=W)
                        listBox.heading("start",text="start",anchor=W)
                        listBox.heading("endpoint",text="endpoint",anchor=W)
                        listBox.heading("trainname",text="trainname",anchor=W)
                        listBox.heading("trainnumber",text="trainnumber",anchor=W)
                        listBox.heading("arrival",text="arrival",anchor=W)
                        listBox.heading("departure",text="departure",anchor=W)
                        listBox.heading("line",text="line",anchor=W)
                        listBox.heading("journey_date",text="journey_date",anchor=W)
                        listBox.heading("coachtype",text="coachtype",anchor=W)
                        listBox.heading("coachno",text="coachno",anchor=W)
                        listBox.heading("cost",text="cost",anchor=W)
                        listBox.heading("seatno",text="seatno",anchor=W)
                        listBox.heading("train_type",text="train_type",anchor=W)
                        
                        
                        show()
                                                
                           
                        
                                                
                        
                        
                        
                        
                        
                        
                        
                    b5=Button(root,text="GO TO SERVER",command=server,height=5,width=20,bd=6,font=("Bold",50),fg="black",bg="orange")
                    b5.place(x=400,y=200)
                else:
                    messagebox.showinfo("","incorrect")
                    exitbutton=Button(root,text="Exit",font=("Bold",20),fg="black",bg="orange",command=root.destroy)
                    exitbutton.place(x=120,y=200)
                l2.destroy()
                l3.destroy()
                e1.destroy()
                e2.destroy()
                b4.destroy()
                
            l1.destroy()
            b2.destroy()
            b3.destroy()
            l2=Label(root,text="username:",font=("Bold",12),fg="black",bg="orange")
            l2.place(x=300,y=300)
            l3=Label(root,text="password:",font=("Bold",12),fg="black",bg="orange")
            l3.place(x=600,y=300)
            e1=Entry(root,bd=6)
            e1.place(x=400,y=300)
            e2=Entry(root,bd=6)
            e2.place(x=700,y=300)
            b4=Button(root,text="Login",command=login,height=5,width=20,bd=6,font=("Bold",12),fg="black",bg="orange")
            b4.place(x=500,y=500)
        def client():
            exitbutton.destroy()
            b2.destroy()
            b3.destroy()
            ll.destroy()
            def create_ticket():
               no=e8.get()
               seat=str(no)
               seat1=int(seat)
               type1=e20.get()
               #print(seat1)
               seat2=str(type1)
               #print(seat2)
               cost1=0
               random1=0
               if seat2=="rajdhani":
                cost1=seat1*2500
               else:
                cost1=seat1*1500
               qwer=Label(root,text=str(cost1),font=("Bold",12),fg="black",bg="orange")   #########
               qwer.place(x=1200,y=200)
               
               
               
               def back():
                qwer.destroy()
                l4.destroy()
                l5.destroy()
                l6.destroy()
                l7.destroy()
                l8.destroy()
                l9.destroy()
                l10.destroy()
                l11.destroy()
                l12.destroy()
                l13.destroy()
                l14.destroy()
                l15.destroy()
                l16.destroy()
                l17.destroy()
                l18.destroy()
                l19.destroy()
                l20.destroy()
                l21.destroy()
                l22.destroy()
                l23.destroy()
                l24.destroy()
                l25.destroy()
                e3.destroy()
                e4.destroy()
                e5.destroy()
                e6.destroy()
                e7.destroy()
                e8.destroy()
                e9.destroy()
                e10.destroy()
                e11.destroy()
                e12.destroy()
                e13.destroy()
                e14.destroy()
                e15.destroy()
                e16.destroy()
                e17.destroy()
                e18.destroy()
                e19.destroy()
                e20.destroy()
                e21.destroy()
                e22.destroy()
                b6.destroy()
                backbutton.destroy()
                tab2()
               backbutton=Button(root,text="back",height=1,width=10,bd=6,font=("Bold",12),fg="black",bg="orange",command=back)
               backbutton.place(x=650,y=500)
               a1=e3.get()  #name
               a2=e4.get()  #adharno
               a3=e5.get()  #phoneno
               a4=e6.get()  #email
               a5=e7.get()  #gender
               a6=e8.get()  #no of seat
               a7=e9.get()  #child
               a8=e10.get()  #adult
               a9=e11.get() #from
               a10=e12.get() #to
               a11=e13.get()#trainname
               a12=e14.get()#train number
               a13=e15.get()#arrival
               a14=e16.get()#departure
               a15=e17.get()#line
               a16=e18.get()#date
               a17=e19.get()#coach type
               a18=e20.get()
               a19=e21.get()
               a20=e22.get()   #traintype
               connect1=pymysql.connect(host="localhost",user="root",password="12345",database="reservation")
               con=connect1.cursor()
               
               sql="INSERT INTO record(name,adharno,phoneno,email,gender,noofseat,child,adult,start,endpoint,trainname,trainnumber,arrival,departure,line,journey_date,coachtype,coachno,cost,seatno,train_type) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"
               val=(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,cost1,a19,a20)
               con.execute(sql,val)
               connect1.commit()
               messagebox.showinfo("information","Record inserted successfully...")
               e3.delete(0,END)
               e4.delete(0,END)
               e5.delete(0,END)
               e6.delete(0,END)
               e7.delete(0,END)
               e8.delete(0,END)
               e9.delete(0,END)
               e10.delete(0,END)
               e11.delete(0,END)
               e12.delete(0,END)
               e13.delete(0,END)
               e14.delete(0,END)
               e15.delete(0,END)
               e16.delete(0,END)
               e17.delete(0,END)
               e18.delete(0,END)
               e19.delete(0,END)
               e20.delete(0,END)
               e3.focus_set()
               connect1.close()
            l4=Label(root,text="Ticket",fg="black",bg="orange",font=("Bold",50))
            l4.place(x=550,y=0)   
            l5=Label(root,text="name:",font=("Bold",12),fg="black",bg="orange")
            l5.place(x=20,y=100)
            l6=Label(root,text="adhare.no:",font=("Bold",12),fg="black",bg="orange")
            l6.place(x=10,y=150)
            l7=Label(root,text="phone.no:",font=("Bold",12),fg="black",bg="orange")
            l7.place(x=10,y=200)
            l8=Label(root,text="email:",font=("Bold",12),fg="black",bg="orange")
            l8.place(x=10,y=250)
            l9=Label(root,text="gender:",font=("Bold",12),fg="black",bg="orange")
            l9.place(x=300,y=100)
            l10=Label(root,text="no of seat:",font=("Bold",12),fg="black",bg="orange")
            l10.place(x=300,y=150)
            l11=Label(root,text="child:",font=("Bold",12),fg="black",bg="orange")
            l11.place(x=300,y=200)
            l12=Label(root,text="adult:",font=("Bold",12),fg="black",bg="orange")
            l12.place(x=300,y=250)
            l13=Label(root,text="from:",font=("Bold",12),fg="black",bg="orange")
            l13.place(x=550,y=100)
            l14=Label(root,text="to:",font=("Bold",12),fg="black",bg="orange")
            l14.place(x=550,y=150)
            l15=Label(root,text="train name:",font=("Bold",12),fg="black",bg="orange")
            l15.place(x=550,y=200)
            l16=Label(root,text="train number:",font=("Bold",12),fg="black",bg="orange")
            l16.place(x=550,y=250)
            l17=Label(root,text="arrival:",font=("Bold",12),fg="black",bg="orange")
            l17.place(x=800,y=100)
            l18=Label(root,text="departure:",font=("Bold",12),fg="black",bg="orange")
            l18.place(x=800,y=150)
            l19=Label(root,text="line:",font=("Bold",12),fg="black",bg="orange")
            l19.place(x=800,y=200)
            l20=Label(root,text="date:",font=("Bold",12),fg="black",bg="orange")
            l20.place(x=800,y=250)
            l21=Label(root,text="coach type:",font=("Bold",12),fg="black",bg="orange")
            l21.place(x=1050,y=100)
            l22=Label(root,text="coach no:",font=("Bold",12),fg="black",bg="orange")
            l22.place(x=1050,y=150)
            l23=Label(root,text="cost:",font=("Bold",12),fg="black",bg="orange")
            l23.place(x=1050,y=200)
            l24=Label(root,text="seat no:",font=("Bold",12),fg="black",bg="orange")
            l24.place(x=1050,y=250)
            l25=Label(root,text="train type:",font=("Bold",12),fg="black",bg="orange")
            l25.place(x=10,y=300)
            e3=Entry(root,bd=7)
            e3.place(x=130,y=100)
            e4=Entry(root,bd=7)
            e4.place(x=130,y=150)
            e5=Entry(root,bd=7)
            e5.place(x=130,y=200)
            e6=Entry(root,bd=7)
            e6.place(x=130,y=250)
            e7=Entry(root,bd=7)
            e7.place(x=400,y=100)
            e8=Entry(root,bd=7)
            e8.place(x=400,y=150)
            e9=Entry(root,bd=7)
            e9.place(x=400,y=200)
            e10=Entry(root,bd=7)
            e10.place(x=400,y=250)
            e11=Entry(root,bd=7)
            e11.place(x=650,y=100)
            e12=Entry(root,bd=7)
            e12.place(x=650,y=150)
            e13=Entry(root,bd=7)
            e13.place(x=650,y=200)
            e14=Entry(root,bd=7)
            e14.place(x=650,y=250)
            e15=Entry(root,bd=7)
            e15.place(x=900,y=100)
            e16=Entry(root,bd=7)
            e16.place(x=900,y=150)
            e17=Entry(root,bd=7)
            e17.place(x=900,y=200)
            e18=Entry(root,bd=7)
            e18.place(x=900,y=250)
            e19=Entry(root,bd=7)
            e19.place(x=1150,y=100)
            e20=Entry(root,bd=7)
            e20.place(x=1150,y=150)
            e21=Entry(root,bd=7)
            e21.place(x=1150,y=250) 
            e22=Entry(root,bd=7)
            e22.place(x=130,y=300)
            b6=Button(root,text="CREATE",height=1,width=10,bd=6,font=("Bold",12),fg="black",bg="orange",command=create_ticket)
            b6.place(x=450,y=500)
            
             
            
            
        b2=Button(root,text="Ticket",font=("Bold",50),fg="black",bg="orange",bd=6,command=client)
        b2.place(x=300,y=450)
        exitbutton=Button(root,text="Exit",font=("Bold",50),fg="black",bg="orange",bd=6,command=root.destroy)
        exitbutton.place(x=650,y=450)
        b3=Button(root,text="Server",font=("Bold",50),fg="black",bg="orange",bd=6,command=password)
        b3.place(x=1000,y=450)
        
        
    l1=Label(root,text="Railway Reservation",font=("Bold",50),fg="black",bg="orange",bd=6)
    l1.place(x=450,y=0)
    
    b1=Button(root,text="click to proceed",font=("Bold",50),command=tab2,fg="black",bg="orange",bd=6)
    b1.place(x=500,y=400)
tab1()
root.mainloop()